# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6b5e5f1927e38444c2bf6acca3e2b825ca6c28685909b71c0d9d169cf72c3f5f731a2d2a66416f544f83f4c76861b8ab6303638391e4d7d83d1e468a5e41a0e

test:
  secret_key_base: a5bc393d65b81b6ab013a6618ebe53eaecc4ec4a2afd25dc319739b7d65866bac2a33dec2032d4c808ba523b97a545466d3981712701784e6ba9f295ac9cae00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
